# Generated by Django 4.2.20 on 2025-04-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('OTRO', 'Otro')], max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('microchip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('allergies', models.TextField(blank=True)),
                ('special_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petcare.owner')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_reason', models.CharField(max_length=200)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('veterinarian', models.CharField(max_length=100)),
                ('prescribed_meds', models.TextField(blank=True)),
                ('next_checkup', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='petcare.pet')),
            ],
            options={
                'verbose_name_plural': 'Historiales Médicos',
            },
        ),
    ]
