# Generated by Django 4.2.20 on 2025-05-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='petcare.pet'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
