# Generated by Django 4.2.20 on 2025-05-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_alter_medicalrecord_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_records/attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_attachments', to='petcare.medicalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='petcare.medicalattachment'),
        ),
    ]
